name: 'dbt_athena_iceberg'
version: '1.0.0'

profile: 'dbt_athena_iceberg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:

  dbt_athena_iceberg:

    landing_zone:
      +materialized: view
      +schema: landing_zone
    
    bronze:
      +materialized: view
      +schema: bronze

    silver:
      +materialized: table
      +schema: silver